/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.davidemonnati.cardgame;

import it.unicam.cs.pa.davidemonnati.cardgame.model.InteractivePlayer;
import it.unicam.cs.pa.davidemonnati.cardgame.model.Player;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;

public class App {
    private static final BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
    private final Game game;

    public App(Game game) {
        this.game = game;
    }

    public void start() {
        game.play();
    }

    public static void main(String[] args) {
        try {
            createGame().start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static App createGame() throws IOException {
        List<Player> players = createPlayers();
        return new App(new GameController(players));
    }

    private static List<Player> createPlayers() throws IOException {
        List<Player> players = new ArrayList<>();
        System.out.println();
        for (int i = 0; i < 2; i++) {
            System.out.println("Creazione player " + (i + 1) + ": ");
            System.out.println("Inserisci username: ");
            String username = br.readLine();
            players.add(new InteractivePlayer(i, username));
            System.out.println("\n");
        }
        return players;
    }
}
